### PR TITLE
Update new version 2.2 PS multishop

### PR DESCRIPTION
**Pull request by amarpanday**
I have update ps multishop new version sendinblue-v2.2

### CODE REVIEW

**Comment by amarpanday** [comment]
Hi

We are about to launch our new version of sendinblue plugin that is compatible for multishop and in process of upgradation we have to alter our table "ps_sendin_newsletter". So we have added upgradation script and tested our query but we are not able to test it with addons.
 
We needed one favor from you to check our "upgradation code". Please check and send us your valuable feedback .
 
Thanks
Amar Pandey(Sendinblue)

**Comment by Quetzacoalt91** [comment]
Hi @amarpanday,

About your upgrade file, this functionality works from PrestaShop 1.5.  If you want to make it work on PS 1.4, you have to add a manual upgrade.I have already made a commit in another module for this purpose: https://github.com/PrestaShop/payulatam/commit/81b0f85c8ba6a6f4a177b1f7957a041bf30c950b

You can reuse and adapt it for your needs. :)

**Comment by Quetzacoalt91** [comment]
Here are a few comments regarding the modifications sent:
* In your module constructor, you can check if multishop is enabled with the function Shop::isFeatureActive(). For PS 1.4, if it is called after the backward compatibility inclusion, it will also work by returning false immediately.
* **sendinblue.php**
  * In the function sendTestSmsCampaign(...), the ```exit();``` will never be executed.
  * l.2564: Do not call CustomerCore but Customer, or the script will crash on PS 1.4.
  * function subscribeByruntime(): When you try to create an instance of customer or addresses, verify them with Validate::isLoadedObject()
  * l.2639 & 2767: ```isset($id_shop_group)``` test is already included in ```!empty($id_shop_group)```
  * This code can be found multiple times in your PR:
```php
		$id_shop_group = !empty($this->id_shop_group) ? $this->id_shop_group : 'NULL';
		$id_shop = !empty($this->id_shop) ? $this->id_shop : 'NULL';

		if ($id_shop === 'NULL' && $id_shop_group === 'NULL')
			$condition = '';
		elseif ($id_shop_group != 'NULL' && $id_shop === 'NULL')
			$condition = 'AND id_shop_group ='.$id_shop_group;
		else
			$condition = 'AND id_shop_group ='.$id_shop_group.' AND id_shop ='.$id_shop;
```
Maybe you should have made a function designed to create these SQL conditions.
  * Same comment for:
```php
		if (version_compare(_PS_VERSION_, '1.5', '>='))
			$condition = 'AND `id_shop_group` = '.pSQL($id_shop_group).'';
		else
			$condition = '';
```
  * In the function **enableSendinblueBlock()**, was ```$this->active``` not enough for your test ? Instead of ```$sendin_status = Db::getInstance()->getRow('SELECT `active` FROM `'._DB_PREFIX_.'module` WHERE `name` = \''.pSQL('sendinblue').'\'');```

**Comment by Quetzacoalt91** [comment]
For your information, the upgrade file works properly. :smile:

**Comment by amarpanday** [comment]
Hi @Quetzacoalt91
I am waitting yours response regarding sendinblue multistore version.

**Comment by Quetzacoalt91** [comment]
Hi @amarpanday,

Thanks, your PR has just been merged and should be available tomorrow.

Regards

**Pull request merged**
